version: '3.9'

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  static:
    driver: local


services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/srv/www/frontend
    command: "npm start"

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/srv/www/backend
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./environment/.env
    command: "python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4:6.19
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
