# Generated by Django 4.2.2 on 2023-06-18 08:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='uuid4',
                    ),
                ),
                (
                    'room_name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='название комнаты'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='uuid4',
                    ),
                ),
                ('created_at', models.DateTimeField(verbose_name='дата отправки')),
                ('message', models.TextField(verbose_name='сообщение')),
                (
                    'chat',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='chat.chatmodel',
                        verbose_name='чат',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
